archive_viewer/archive_viewer.py, archive_viewer/archive_viewer.ui, archive_viewer/mixins/axis_table.py
This PR gives functionality to the QDateTimeEdits in the Axes tab of the Archive Viewer:
The values in the QDateTimeEdits will be updated to reflect changes to the plot's X-Axis. Changing the values in these widgets also makes the expected change to the plot's X-Axis.
Caveats:
- If the user is editing a QDateTimeEdit's value, then it will not reflect changes to the X-Axis. This would be disruptive and prevent the user from setting the desired range value.
- If the left timestamp is larger than the right timestamp, then the smaller value is set as the X-Axis range "minimum", regardless of being set in the "maximum" QDateTimeEdit. And vice versa.
=> ENH: Update X-Axis from QDateTimeEdits

archive_viewer/archive_viewer.py, archive_viewer/archive_viewer.ui, archive_viewer/mixins/axis_table.py, archive_viewer/mixins/traces_table.py, archive_viewer/table_models/axis_model.py, archive_viewer/widgets/item_delegates.py
Includes changes from #17 
- Remove the Delete Axis button from the Axes tab:
- This includes removing the associated slot from the AxisTableMixin
- Add an inline "row delete" button to each row:
- This inline button is the same as the inline row deletion button in the Traces tab, meaning that they look and behave the same way
- Change to DeleteRowDelegate: 
- Tooltip changed from "Delete Trace" to "Delete Row" to make it more general
- Change to ArchiverAxisModel.removeAtIndex:
- If there is only one axis remaining, then deleting it would cause the plot to break
- Instead, the model adds a new axis and removes the other one. This has the affect of resetting the only row and not breaking the plot
- This captures an edge case
=> ENH: Replace Delete Axis button with inline button

.gitignore, archive_viewer/archive_viewer.py, archive_viewer/archive_viewer.ui, archive_viewer/av_file_convert.py, archive_viewer/config.json, archive_viewer/config.py, archive_viewer/mixins/__init__.py, archive_viewer/mixins/file_io.py, archive_viewer/mixins/traces_table.py, archive_viewer/table_models/axis_model.py, archive_viewer/table_models/curve_model.py, launch_archive_viewer.bash
Create a tool to manage importing, exporting, and converting Archive Viewer config files. The tool works as a standalone CLI tool as well as an importable module.
The import & export capabilities are straight forward: given a filename either read in the data or write saved data to the file. The imported file can be of 2 types (.xml and .pyav), but the file extension is ignored if it is in the right format. The tool allows for converting from Java-based Archive Viewer config files to PyDM-based Archive Viewer files.
This Pull Request also implements importing/exporting into the Archive Viewer, making use of the tool described above. File IO is attached to 2 buttons on the application marked "Test Import" and "Test Export". This functionality should be moved eventually.
Changes to the …
=> Archive Viewer file import and export

archive_viewer/av_file_convert.py, archive_viewer/mixins/file_io.py
2 small bug fixes for file IO:
1. In av_file_convert.py : convert_data()
a. For all curves, lineWidth was being converted to a float, which is partially correct since Java saves these as floats, but then they need to be converted to ints after for BasePlotCurveItem to make use of them
b. Solution: `float(pv_in['draw_width'])` =>  `int(float(pv_in['draw_width']))`
2. In file_io.py : set_time_on_datetime():
a. Capture unaccounted for AttributeError when relative date time strings don't include an absolute time:
E.g. `-3d` vs `-3d 8:00:00`
=> FIX: Small Bug Fixes for File IO

archive_viewer/archive_viewer.py, archive_viewer/archive_viewer.ui, archive_viewer/config.json, archive_viewer/config.py, archive_viewer/mixins/axis_table.py, archive_viewer/mixins/file_io.py, archive_viewer/mixins/traces_table.py, archive_viewer/table_models/axis_model.py, archive_viewer/table_models/curve_model.py
Added a footer to the bottom of the application to provide 4 functions:
1. Display the URL for the Archiver Tool that is being used by the application
2. Display the current date and time on the application. This may help if users share screenshots of their application
3. Display the current release version of the application. This relies on the git tag
4. Display an in-app logger. This shows any errors, warnings, or messages that the user may want to know about. This is also a quick way for the user to confirm if the application is working
=> ENH: UI Footer

archive_viewer/mixins/traces_table.py, archive_viewer/table_models/curve_model.py
Relies on PR #19 and PyDM PR [#1096](https://github.com/slaclab/pydm/pull/1096)
Makes use of the Style column in the traces table. There are 2 options available to the user: Direct (default) and Step.
The Direct option is the same as what we've seen before: lines drawn directly from y-value to y-value.
The Step option will show horizontal lines extending to the right of y-values, continuing until a new y-value, where there will be a vertical line connecting the two. 
I also removed all of the columns used for thresholds & limits as those are unnecessary without the bar graph styling.
=> ENH: Style column in traces_table sets curve's stepMode

archive_viewer/archive_viewer.py, archive_viewer/mixins/file_io.py, archive_viewer/table_models/curve_model.py, launch_archive_viewer.bash
Add functionality for macros and arguments. The application will check both macros and arguments for a file to import from, and for lists of PVs to show on startup.
- INPUT_FILE : str
- File path to import from on startup
- PV or PVS  : str | list
- A channel or list of channels to show on startup
- -i, --input_file : str
- File path to import from on startup
- -p, --pvs : str | list
- A channel or list of channels to show on startup
Since we can only specify one input file, the argument is given priority over the macros. However, the list of PVs will concatenate values from both macros and arguments. If a channel is listed in multiple places (macro, argument, and/or imported file) it will only be included once.
E.g.
`pydm -m '{"PVS": ["KLYS:LI22:31:KVAC", "KLYS:LI22:41:KVAC"]}' …
=> ENH: Macro & Argument Functionality

archive_viewer/archive_viewer.py, archive_viewer/mixins/axis_table.py, archive_viewer/mixins/traces_table.py, archive_viewer/table_models/axis_model.py, archive_viewer/table_models/curve_model.py, archive_viewer/widgets/item_delegates.py
Builds on #24 
Requires the pydm PR to go through, but allows the user to cleanly navigate adding, removing, and hiding axes; as well as hiding/removing curves and it properly hiding their axes. Finally, it defaults new curves to the correct axes upon creation and allows for easy switching between axes.
=> ENH: Fixing Axes functionality on the Archive Viewer

archive_viewer/archive_viewer.py, archive_viewer/table_models/axis_model.py
This was a suggestion of Jesse's on the PyDM side, so I made this small change to accommodate what would be missing from PyDM if I made those changes
=> FIX: Shifted axis "hidden" attribute getter to Archive Viewer side 

archive_viewer/table_models/curve_model.py
Old: Would require formulas to reference rows strictly above them. This is hard to understand from the user perspective, but would make ensuring no recursion very easy.
New: DFS to check dependencies making sure we never reach the original curve again.
To Do: how to handle importing Formulas that are not imported in dependency order?
=> FIX: Formula Dependency Checker Using DFS

archive_viewer/mixins/traces_table.py, archive_viewer/table_models/curve_model.py, archive_viewer/widgets/archive_search.py
New TracesTableView object that extends QTableView, handles drag and drop events to be able to take in PV names from PV search. Updates its model to set the curve.
It takes a second to load, unknown fix. Added a logger.info to reassure user that the app is just thinking about it rather than making them feel nothing is happening
Dragging and dropping any number of PVs anywhere on the viewer appends them to the end of the table.
Added an "Add PVs" button that does the exact same thing as dragging and dropping the selected names.
Double clicking will select and input a single PV name into the table.
Better search function - hitting enter or return prompts a search rather than having to manually click a button on screen. Also, using '?' works as a buffer character to help search for channel …
=> ENH: Drag and Drop PVs from PV search

archive_viewer/widgets/item_delegates.py
This PR does 2 things:
1. Fixes a bug in EditorDelegate:
a. When implementing a QStyledItemDelegate, I forgot to reimplement the method `updateEditorGeometry`. Without this function, the editors don't update properly on `dataChanged` signals. This should solve some problems I've been having with the delegates
3. ComboBoxDelegate to subclass EditorDelegate:
a. All other delegates subclass EditorDelegate already
b. Avoided setting up ComboBoxDelegate this way because it seemed to cause issues in initial testing, turns out it was just the bug with EditorDelegate that is mentioned above and fixed
=> FIX: ComboBox Subclasses EditorDelegate

archive_viewer/table_models/curve_model.py
At some point I removed a line that unlinked an old APCI when replacing it with an FCI, leading to axes thinking they had extra curves attached. When trying to autohide, they wouldn't, thinking they still had the old APCI attached. Now we unlink it so autohide works
=> FIX: autoVisible works with FCIs

archive_viewer/table_models/curve_model.py
Slap a "px" onto necessary strings and it allows the item delegates combo box to read the value in directly rather than try to set indices incorrectly.
=> FIX: Line Width and Symbol Size are in sync between table view and model

.gitignore, archive_viewer/av_file_convert.py, archive_viewer/examples/FormulaExample.trc, archive_viewer/examples/PlotConfigExample.trc, archive_viewer/mixins/file_io.py
Added debugger to gitignore for our QOL.
Deprecated .pyav extension in favor of .trc
Added Formula and Plot Config Import example .trc files to a new directory Archive-Viewer/archive_viewer/examples
Yes, they still import properly.
Can add more if wanted.
=> ENH: Switched every .pyav reference to .trc and added examples

archive_viewer/mixins/traces_table.py, archive_viewer/table_models/curve_model.py, archive_viewer/widgets/archive_search.py
Users can paste in a list of pvs separated by any white space (space, newline, tab, etc) or commas, and we will detect that there are multiple curves being inserted, split them up, and insert them separately.
Uses a simple regex to split, so our exact split delimiters can change but currently set to '[\s,]+' to detect white space and commas.
Potential issue: sometimes formulae have spaces i.e. f://{A} + {B} and this will split on those spaces.
This uses the same functionality as dragAndDropPV to insert multiple PVs at a time, and any curves with typos will be treated as if they were typed one at a time by the user, meaning a new row will form, we will attempt to connect and we wont be able to on a misspelled PV
=> ENH: Copy Paste Multiple PV Functionality

trace/mixins/traces_table.py, trace/table_models/axis_model.py, trace/table_models/curve_model.py
Couldn't get away from this work huh. Well I've created a new fork to handle the fact that there were a million untracked files in my local as a result of the name change. I copied over my changes from my open PR EGUAxes on my old repo, and it works to my knowledge. Not sure what has been added in the past week so please double check for me I didn't break anything, but I believe there were no actual merge conflicts, only that the files the old PR were changing no longer existed. 
Hope this works!
=> ENH: EGU Axes

trace/mixins/traces_table.py, trace/table_models/axis_model.py, trace/table_models/curve_model.py
Some minor restructuring & reformatting in curve_model
- Removed `dataChanged` signal from `set_data` and fixed the reason it was being used
- Removed changing trace's label on when new Channel is set, this doesn't work as expected with EGU Axes
- Removed passing curve as argument in setAxis because we can get the curve with `self.sender()`
- Reformatted `__contains__`
- In `set_data`, won't allow users to use duplicate PVs or formulas (new)
=> FIX: Minor fixes

trace/mixins/traces_table.py, trace/table_models/curve_model.py
Relies on https://github.com/slaclab/pydm/pull/1108
Displays the connection status for both live and archive channels for each curve. This is shown in 3 ways in the curve table, the Live Data or Archive Data cell for the curve will:
1. Become disabled if the channel is disconnected
2. Have a red background if the channel is disconnected
3. Have a tooltip stating that the associated channel is disconnected, if it is disconnected
The checkbox in these cells will still display as checked even if the channels are disconnected, which may cause some confusion, but possibly less than having an empty box because it is hard to tell it's been disabled.
=> ENH: Display Connection Status for Curve Channels

trace/mixins/traces_table.py, trace/table_models/curve_model.py
Builds on #37 and relies on https://github.com/slaclab/pydm/pull/1111
Displays the connection status for both live and archive channels for formula curves. This is shown in 3 ways in the curve table, just like the referenced PR.
This PR also adds automatic hiding of curves if they are disconnected from both live and archive channels.
=> ENH: Connection Status for Formula Curves

.gitignore, docs/how_to/io.md, trace/examples/stp_conversion.stp, trace/examples/xml_conversion.xml, trace/mixins/file_io.py, trace/mixins/plot_config.py, trace/trace_file_convert.py
This PR adds the ability to import and convert StripTool files (*.stp) to Trace files (*.trc). This works the same as importing and converting the Java-based Archive Viewer save files. It should be very straight forward.
Minor Changes:
- When importing files, the file conversion is handled by the converter object rather than needing to be called separately. This let's the converter handle converting xml data vs stp data. Just faster/easier.
- Removed context menu from the plot. Right clicking is now a panning tool.
Bug Fix:
Fixed a bug when importing Plot Configuration options. Functions being called expected bools, but were given Truey/Falsey values. Just converted the values to bools to fix this issue.
Docs:
Added importing StripTool to documentation. Also included example Archive …
=> ENH: Import and Convert StripTool Files

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, README.md
Fix the links to the issue templates in the README so they have labels and titles. Add validation to issue templates so that some fields are required. This is the description fields, steps to reproduce, and what the user would like to see.
=> DOC: One More Change to README and Issue Templates

docs/api_reference/trace.md, docs/how_to/file_conversion.md, launch_trace.bash, trace/main.py, trace/mixins/traces_table.py, trace/table_models/curve_model.py, trace/trace_file_convert.py
Adds the ability to pass multiple files into the file conversion tool to convert them all at once. Prints individual error messages if anything goes wrong so that users know which file(s) failed.
Also found some bugs with the launch script & passing arguments. They should be fixed now. Plus macros should work properly now.
=> ENH: Convert Files With Batch Processing

trace/trace_file_convert.py
I found where the duplicate logging was coming from. A second logger was always being created in `trace_file_convert.py` when it should have only been creating a logger if one didn't already exist.
Solution:
Get the logger (same name PyDM uses) and check if it has handlers. If handlers don't exist, then add them.
=> FIX: Remove Duplicate Logging

trace/main.py, trace/main.ui, trace/mixins/plot_config.py, trace/tests/test_data/test_file.trc, trace/tests/test_mixins/test_plot_config.py, trace/widgets/item_delegates.py
Changes in PR ([Jira issue](https://jira.slac.stanford.edu/secure/RapidBoard.jspa?projectKey=TRC&rapidView=207)):
- Scientific Notation Validation should allow numbers in format '1e5' (TRC-68)
- Remove main_plot from the Time Plots tabwidget (TRC-71)
- Replace the 30s quick range selection button with 1d (TRC-72)
- Auto-scroll refresh rate spinbox should be an int instead of a float (TRC-73)
- Opacity slider should be more clear that it is gridline opacity (TRC-74)
- Move the logger from the footer into a new tab in the properties section (TRC-75)
=> ENH/FIX: Minor UI Fixes/Changes

trace/main.py, trace/trace_file_convert.py
Fixing a bug caused by batch conversion feature.
PathAction was taking in a list or a string, but only treating it as a list. This resulted in it creating a Path object for every character in the provided string. My solution is to check if the given value is a string, and if it is, then PathAction wraps it in a list first.
The second issue PathAction had, is that it only ever returned a list. So FileIOMixin.save_file_import would throw an error because it expected a Path object. My solution is to unpack the list before calling save_file_import.
=> FIX: Fixing input_file argument for trace (TRC-66)

trace/mixins/axis_table.py, trace/table_models/axis_model.py
[Related issue](https://jira.slac.stanford.edu/secure/RapidBoard.jspa?rapidView=207&projectKey=TRC&view=detail&selectedIssue=TRC-79#)
There is no need for the name and the label to be different for y-axes. Combining the columns so that editing the name also edits the label.
This will fix some confusion that users have had.
=> ENH: Combine Y-axis Name & Label Columns

trace/table_models/axis_model.py, trace/table_models/curve_model.py, trace/tests/conftest.py, trace/tests/test_data/test_file.trc, trace/tests/test_mixins/test_traces_table.py, trace/tests/test_table_models/test_axis_model.py, trace/tests/test_table_models/test_curve_model.py, trace/tests/test_widgets/test_table_widgets.py, trace/trace_file_convert.py, trace/widgets/archive_search.py
Adding a lot of tests for:
- Axis table model
- Curves table model
- Axis tab mixin
- Curves tab mixin
- ColorButton
Made a few minor fixes to models as well:
- Removed all references to QVariant as they are incorrectly used
- In ArchiverAxisModel.set_model_axes
- Removed an extra axis that was always getting added at the end, but it shouldn't have been there
- In some instances where an exception is being passed straight into the logger, I convert the exception to a string for easier testing
- Fixed ArchiverCurveModel.flags to correctly return Qt.NoItemFlags if the given index is invalid
=> TST/FIX: Add Tests for Models & Widgets

trace/main.ui
Fixing a mistake that was made when creating the quick timespan button for 1 day (labeled '1d'). The button was mistakenly left out of the `timespan_btns` button group, resulting in:
- the toggling not being exclusive to the other timespan buttons
- the button having no functionality when clicked/toggled
The solution was simply to add it in designer.
=> FIX: Add 1d Button to timespan_btns Button Group

trace/main.py, trace/tests/test_main.py, trace/tests/test_table_models/test_axis_model.py, trace/tests/test_table_models/test_curve_model.py
Adding tests for `main.py`. Also adding tests for `ArchiverAxisModel.set_model_axes` and `ArchiverCurveModel.set_model_curves` for passing empty arguments.
The only fix that came up while writing tests was in `main.py`, changing `from subprocess import run` to `import subprocess`.
=> TST: Tests For main.py

trace/main.py, trace/main.ui, trace/tests/conftest.py, trace/tests/test_widgets/test_archive_search.py, trace/tests/test_widgets/test_data_insight_tool.py, trace/widgets/__init__.py, trace/widgets/data_insight_tool.py, trace/widgets/frozen_table_view.py
Created a tool to view and export all data points shown on the plot. As of right now, the method of opening the tool is just a button on the top left of the main display labeled "Data Insight Tool". This should probably be moved somewhere else, but I'm not sure where.
The widget consists of 4 main widgets:
1. The PV Selection Combobox
a. Only shows PVs for ArchiverPlotCurveItems (does not work for FormulaCurveItems yet)
2. Refresh Data Button
a. Useful for if the range on the plot's x-axis changes. Prompt's data fetching as needed.
3. Export Data Button
a. Prompts user to select a file and format to write the data to.
b. Allows for .csv, .mat, & .json as of right now
4. TableView
a. Shows all the data as well as its source (live or archive)
b. The leftmost column is the datetime in ISO …
=> ENH: Data Insight Tool

.gitignore, trace/main.py, trace/main.ui, trace/tests/test_main.py
Adds Save Plot Image button to display.
Clicking opens a file dialog to allow user to set custom filename and location. Default location is user home.
SWAPPS-80
=> Save Plot Image

trace/widgets/item_delegates.py
This affects ScientificNotationDelegate, which is used in the Y axis range fields.
Sets the limit to the number of digits after the decimal to 6. This should affect both when the value changes automatically - when the plot is resized, or when the user manually inputs a value.
resolves #125
=> ENH: Limit precision to 6

trace/table_models/curve_model.py
Delete removed curves. Wasn't implemented before so the curves just persist in purgatory.
Also, I can't remember the reasoning behind redrawing the plot multiple times. Seems unnecessary. Removing it for now.
=> FIX: Delete removed curves

trace/mixins/plot_config.py
Fixing Trace's mouse mode feature in the Plot Config tab. The problem was that it was only setting the mouse mode for the main viewbox of the plot and not all of them.
This makes sure to use the multi-axis-viewbox's method for changing mouse mode.
=> FIX: Fixing mouse mode to enable panning

trace/main.py
Displays a line extending from a curve's rightmost point (latest) to infinity. This way the user will always see the curve's latest point, even if its data hasn't changed in a long time.
Relies on https://github.com/slaclab/pydm/pull/1167
=> ENH: Enable plot's extension lines

trace/main.py, trace/main.ui, trace/tests/conftest.py, trace/tests/test_main.py
Adds a "fetch archive" button to allow user to manually prompt for archive fetch.
It checks to see if there is already a request queued.
=> ENH: Implement button to manually trigger archive fetch

trace/ui_redesign_test.py, trace/widgets/__init__.py, trace/widgets/plot_settings.py
Creating a pure python display in `ui_redesign_test.py`. This PR creates a semi-functioning skeleton to replace trace's current design.
Add new PlotSettingsModal widget to open a popup window with all settings for the main plot of the application. This class should probably be renamed as it is not actually a modal.
The code should eventually replace `main.ui` & `main.py`
Related to #135
=> ENH: Begin Trace Redesign

requirements.txt, trace/ui_redesign_test.py
Replaces the placeholder icon for the plot settings button with a settings cog icon.
Credit to @shilorigins for finding the qtawesome icon set.
=> ENH: Use qtawesome icon for plot settings button

trace/widgets/__init__.py, trace/widgets/curve_settings.py, trace/widgets/plot_settings.py, trace/widgets/settings_components.py
Create a settings modal for controlling the look of individual curves. The modal will open to the bottom right of its parent widget, similar to the modal in #137.
- parent: QWidget
- This is the parent object of the modal. Should be whatever button opens the modal
- plot: PyDMArchiverTimePlot
- This is the main plot of Trace
- This is only used for redrawing the plot when the orientation changes. This should probably be done in PyDM instead of here
- curve: TimePlotCurveItem
- The curve item that is controlled by the modal
- Setting the curve's name (label in the legend)
- Color
- Appearance
- Line type (step or direct)
- Style (solid, dotted, dashed, etc.)
- Width
- Symbol
- Shape (circle, star, none, etc.)
- Size
Also created a file containing reused components of the settings modals. …
=> ENH: Add Curve/PV Settings Modal

trace/ui_redesign_test.py, trace/widgets/__init__.py, trace/widgets/axis_settings.py, trace/widgets/plot_settings.py
Add a modal for controlling the settings of an axis. 
The modal class, `AxisSettingsModal`, takes in 3 arguments:
- parent: QWidget
- This is the parent object of the modal. Should be whatever button opens the modal
- plot: PyDMArchiverTimePlot
- This is the main plot of Trace
- This is only used for redrawing the plot when the orientation changes. This should probably be done in PyDM instead of here
- axis: BasePlotAxisItem
- The axis item that is controlled by the modal
The modal contains settings for:
- Changing the axis' orientation (left/right side)
- Enabling/disabling log mode for the axis
- Enabling/disabling gridlines on the axis
- The opacity relies on the opacity slider from the `PlotSettingsModal`. This is done to keep the gridline opacity consistent across the plot
=> ENH: Add Axis Settings Modal

trace/ui_redesign_test.py, trace/widgets/plot_settings.py
- Mimics PR: #17
- Added 2 new rows labeled "Start Time" and "End Time" each with a `QDateTimeEdit` to `PlotSettingsModal`
- When a new date is set for either auto-scrolling will be turned off and the plot's x-axis will be changed
- If the x-axis changes, the values in the `QDateTimeEdit`s also change to reflect the updated x-axis range
- `TraceDisplay` did not have a slot connected to the signal `PlotSettingsModal.auto_scroll_interval_change`
- Now it correctly adjusts the interval of the plot's auto scrolling feature by using the slot `TraceDisplay.set_auto_scroll_interval`
- Set a constant value for the value of `TraceDisplay.disable_auto_scroll_button`
- Reasons for doing this:
- It is set to a non-common value (-2) because -1 is a special value for `QButtonGroup`s
- The value is …
=> ENH: Adding X-Range Controls to Plot Settings

trace/widgets/control_panel.py
Using indicing to iterate was causing half of the indices to become invalid, causing errors.
Disconnecting the signals after closing all children is also important; this way, any error encountered while closing children doesn't disconnect the signals, so the axis continues working and a second call to disconnect doesn't error.
Closes #144
=> BUG: don't iterate using indices in AxisItem.close

trace/ui_redesign_test.py, trace/widgets/control_panel.py, trace/widgets/data_insight_tool.py
- Add the `DataInsightTool` to the UI Redesign (#88)
- The DIT's PV selection box updates when curves are added/removed so that the box only shows the available `ArchivePlotCurveItem`s
- DIT no longer requires the curve model, it gets all data from the plot & archiver tool
- Signal from `ControlPanel` that is emitted whenever a curve is added/removed
- Could be useful in the future
=> ENH: Add DataInsightTool to UI Redesign

trace/ui_redesign_test.py, trace/widgets/control_panel.py
This commit prevents axes / curves from being squished as more are added.
ControlPanel has a minimum width based on the axis list so that the ScrollArea (mostly) only scrolls vertically.  If the window is shrunk or the font size is increased several times, a horizontal scroll bar will appear.
=> STY: contain axis / curve list in ScrollArea

trace/config.py, trace/widgets/data_insight_tool.py
The `DataInsightTool` from #147 was causing the main thread to hang whenever a new curve was added. This came from a caget on a PV that didn't exist, resulting in the thread waiting the whole 5s timeout delay.
Move the caget call to a separate worker thread. The thread is spawned from the `DataVisualizationModel`. The model saves the description as an attribute and will prompt an update of the `DataInsightTool`. The meta_data label will be populated with a "Loading..." message while waiting for a CA response. This will really only be visible when the PV doesn't exist and is waiting to timeout.
- `DataInsightTool.set_meta_data` would throw errors if the user tried a caget call on a PV that doesn't exist. This function was trying to concatenate a `NoneType` with a `str`. Instead I am using …
=> FIX: Fix Main Thread Hanging from caget Call

trace/ui_redesign_test.py, trace/widgets/control_panel.py
Uses the same background color as the plot, and changes the background color of the control panel, to match mock-ups. Adjusts content margins to look even.
Closes [SWAPPS-251](https://jira.slac.stanford.edu/browse/SWAPPS-251)
Before
After
=> GUI: make splitter handle visible

trace/ui_redesign_test.py
This PR adds a menu to the applications menu bar titled "Trace". The Trace menu contains actions that are relevant to the application. All actions added to the Trace menu are also assigned a keyboard shortcut.
The exact actions in the menu are listed below:
- Save, Save As, and Open for trace config files (*.trc)
- Note: these actions don't actually work yet, but these are a place holder
- Save Plot Image
- The Save Plot Image button is removed from the toolbar
- Save ELOG Entry
- The Save ELOG Entry button is removed from the toolbar
- Fetch Archive Data
- Data Insight Tool
- The Data Insight Tool button is removed from the toolbar
closes #126
=> ENH: Trace Menu with Trace Specific Actions

trace/widgets/control_panel.py
Adds a disconnect plug icon which appears when either live or archive data is not connected. When hovering the icon, a tooltip appears for additional description.
=> GUI: Indicator for live and archive connection status

trace/widgets/control_panel.py, trace/widgets/plot_settings.py
Previously, the `x_axis_font_size_spinbox` only affected the font size for ticks on the X-Axis. This PR will set the font size for ticks of all axes. This also sets the font size of new axes to match the font size of existing axes.
This was requested in a meeting in October. Part of the reason behind the request was because Trace looked odd when the font was larger for only one axis.
Closes #74 
Closes [SWAPPS-51](https://jira.slac.stanford.edu/browse/SWAPPS-51)
Before: Only the font size for the X-Axis changed
After: Set the font size for all axes (X & Y)
After: Change the setting name in PlotSettingsModal changed from "X Axis Font Size" to "Axis Tick Font Size"
=> ENH: Tick Font Size Sets Y-Axes Tick Font As Well

trace/file_io/file_handler.py, trace/main.py
- When a file is loaded, adds the filename in the footer next to the archiver url
- Added file_loaded_signal to TraceFileHandler
- On receiving the signal, the main window creates a QLabel with the filename and adds it to the footer, or changes the text if already created
- Removed version, username, and PID so that without loaded filename the footer info only includes node name and archiver url
=> Reduce footer info and add imported filename

trace/widgets/control_panel.py, trace/widgets/formula_dialog.py, trace/widgets/utilities/formula_validation.py
This PR adds support for Formula Curves + Formula Editor 
this pr also adds in a utilities file formula_validation.py which has helper functions to validate formulas in the control panel
Note:
to test this you need to be on this branch of PyDM: https://github.com/slaclab/pydm/pull/1260 
Work still needed on this before merging in:
1. also need to fix an issue where data_insight_tool.py does not like that "FormulaCurveItem' object has no attribute 'address'"
=> ENH: Adds Support for Formula Curves + Formula Editor  

.github/workflows/gh-pages.yml, .github/workflows/run-test.yml, environment.yml, trace/file_io/file_handler.py, trace/file_io/time_parser.py, trace/file_io/trace_file_convert.py, trace/services/elog_client.py, trace/widgets/archive_search.py, trace/widgets/color_button.py, trace/widgets/curve_settings.py, trace/widgets/data_insight_tool.py, trace/widgets/elog_post_modal.py, trace/widgets/settings_components.py
Upgrading the version of Python used to 3.12. This is because SLAC & PyDM are now on 3.12, and it'd be good to keep up with them. These changes were done in the GH workflows and the environment file.
Also translated all previous type hints from the `typing` library to the built-in Python type hints.
=> MNT: Upgrade Python to 3.12

trace/widgets/control_panel.py, trace/widgets/curve_settings.py, trace/widgets/plot_settings.py
* Moved live and archive data option check boxes from control panel to curve settings modal
* Live and archive connection status indicators are still on the control panel, moved them to be inline with label, settings and delete buttons
* Also added legend on by default to this PR
=> Live + archive data moved to curve settings

trace/widgets/control_panel.py
Added a QMessagebox popup to confirm deleting an axis
This makes his harder to accidentally delete an axis
[FEATURE] - Pop up for deleting axis #165
=> Add QMessagebox popup to confirm deleting axis

trace/stylesheets/dark_mode.qss, trace/stylesheets/light_mode.qss, trace/widgets/control_panel.py
When a user creates a new curve, it is added to an axis based on the channels units (if the `.EGU` field is populated). If an axis for that unit does not exist, a new one will be created. The axes will have the unit as the name (e.g. '%', 'bara', 'deg_F').
If a new curve does not have units (formula, no `.EGU` field, no live data) it will be added to a unitless axis named 'Axis 1' or something similar.
This groups like curves onto the same axes, giving the data context. This feature also existed before the UI was redesigned and it'd be nice to bring it back.
Closes SWAPPS-248
=> ENH: New Curves Are Added to Axes Based on Units

trace/widgets/control_panel.py
This PR addressed two errors. 
1. In `AxisItem.set_active`, check that children widgets are `CurveItem`s
2. When `CurveItem`s are moved to a new `AxisItem`, the curve's error bar & extension line remained on the previous axis
=> FIX: Error with AxisItem.set_active & Curve Artifacts Remaining on Previous Axis

trace/widgets/curve_settings.py
Fixes error with `CurveSettingsModal`. The widget would try to reference a non existent property for `FormulaCurveItem`s. This PR adds a check to prevent referencing the property if it doesn't exist.
The error below would come up when opening the settings for a Formula curve:
```
Traceback (most recent call last):
File "/sdf/home/z/zdomke/workspace/trace/trace/trace/widgets/control_panel.py", line 968, in show_settings_modal
self.pv_settings_modal = CurveSettingsModal(self.pv_settings_button, self.plot, self.source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/sdf/home/z/zdomke/workspace/trace/trace/trace/widgets/curve_settings.py", line 40, in __init__
bin_count = curve.optimized_data_bins
^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FormulaCurveItem' object …
```
=> FIX: Hide Bin Count Setting for FormulaCurves
